// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoi3foReEsEkIFHNgrMk96VBRAaVNZvtE',
    appId: '1:388802825089:web:b91c07361ff13f6e847680',
    messagingSenderId: '388802825089',
    projectId: 'white-label-caa9b',
    authDomain: 'white-label-caa9b.firebaseapp.com',
    storageBucket: 'white-label-caa9b.firebasestorage.app',
    measurementId: 'G-97PXFKRPFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJHbc92fDlZcRcwGdmLxinDMhBpoEaOOw',
    appId: '1:388802825089:android:5be7fab3e8149269847680',
    messagingSenderId: '388802825089',
    projectId: 'white-label-caa9b',
    storageBucket: 'white-label-caa9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUBiSt_V8jd3pj9Vw3bRQms2C77Jyzrc4',
    appId: '1:388802825089:ios:470a3a8a5121d683847680',
    messagingSenderId: '388802825089',
    projectId: 'white-label-caa9b',
    storageBucket: 'white-label-caa9b.firebasestorage.app',
    iosBundleId: 'com.example.whiteLabel',
  );
}
